require("packages.impatient")
require("user/plugins")
require("packages.autocmd")
require("packages.lualine")
require("packages/colorschemes")
require("packages/lsp")
require("packages/dap")
require("packages/nvim-tree")
require("packages/auto-pairs")
require("packages.toggleterm")
require("packages.whichkey")
require("packages.project")
require("packages.gitsigns")
-- require("packages.neoscroll")
require("packages.windows")
require("packages.hlargs")
require("packages.symbols-outline")
require("packages.noice")
require("packages.ufo")
require("packages.prettyfold")
require("packages.navic")
require("packages.telescope")
require("packages.indent-blank-line")
require("packages.alpha")
require("user/settings")
require("user/keymaps")
require("packages.treesitter")
require("packages.comment")
require("packages.leap")
require("packages.surround")

if vim.g.neovide then
	vim.opt.guifont = { "ComicCodeLigatures Nerd Font Mono", ":h17" }
	vim.g.neovide_underline_automatic_scaling = 1
	vim.g.neovide_cursor_trail_size = 0.5
end
